name: Run Tests

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - '*'

jobs:
  test:
    name: Run Maven Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 19.0.1
        uses: actions/setup-java@v2
        with:
          java-version: 19.0.1
          distribution: adopt

      - name: Run Maven Tests
        run: mvn test --file pom.xml
