name: Run Tests

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - '*'

jobs:
  test:
    name: Run Maven Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 19.0.1
        uses: actions/setup-java@v2
        with:
          java-version: 19.0.1
          distribution: adopt

      - name: Run Maven Tests
        run: mvn test --file pom.xml

      - name: Build Maven Artifacts
        run: mvn package --file pom.xml      
     
      - name: Set up Docker Buildx (for multi-platform builds)
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker buildx build --platform linux/amd64 -t $DOCKER_USERNAME/tickets-service:latest -f src/main/docker/Dockerfile.jvm .
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      
      - name: Push Docker Image
        run: docker push $DOCKER_USERNAME/tickets-service:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
