name: Run Tests

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - '*'

jobs:
  test:
    name: Run Maven Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 19.0.1
        uses: actions/setup-java@v2
        with:
          java-version: 19.0.1
          distribution: adopt

      - name: Run Maven Tests
        run: mvn test --file pom.xml
      - name: Login to DockerHub and push image
        run: |
          docker login -u $DOCKER_USERNAME --password-stdin <<< $DOCKER_PASSWORD
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          IMAGE_NAME: jancii/users-service:latest
